#include <stdio.h>
#include <stdlib.h>

extern void wasker_main();

long linear_memory_base;
int linear_memory_block_num = 0;
const int LINEAR_MEMORY_BLOCK_SIZE = 64 * 1024;
const int LINEAR_MEMORY_BLOCK_NUM_MAX = 32;

//////////////////////////////////////////////
/// Provide linear memory with Wasm
//////////////////////////////////////////////

long memory_base()
{
  // malloc 32 Block for linear memory
  char *memory = (char *)malloc(LINEAR_MEMORY_BLOCK_SIZE * LINEAR_MEMORY_BLOCK_NUM_MAX);
  linear_memory_base = (long)memory;
  return linear_memory_base;
}

long memory_grow(long num)
{
  int old = linear_memory_block_num;

  // check if there are enough memory
  if (LINEAR_MEMORY_BLOCK_NUM_MAX < linear_memory_block_num + num)
  {
    printf("memory_grow: failed to grow memory\n");
    return -1;
  }

  linear_memory_block_num += num;
  return old;
}

void print(char *ptr, int len)
{
  for (int i = 0; i < len; i++)
  {
    printf("%c", (ptr)[i]);
  }
}

int main()
{
  // Entrypoint of ELF generated by Wasker
  wasker_main();
  return 0;
}