name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run clippy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup
        uses: dtolnay/rust-toolchain@stable
        env:
          LLVM_SYS_150_PREFIX: /home/runner/.wasker/clang+llvm-15.0.0-x86_64-linux-gnu-rhel-8.4
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  test:
    runs-on: ubuntu-latest
    name: Run test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup
        uses: dtolnay/rust-toolchain@stable
        env:
          LLVM_SYS_150_PREFIX: /home/runner/.wasker/clang+llvm-15.0.0-x86_64-linux-gnu-rhel-8.4
      - name: Run test 
        run: cargo test --all -- --nocapture
